package com.hacknite.model.db;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.hacknite.model.response.PlanetResponse;
import com.hacknite.model.response.RocketResponse;

import java.util.List;

@DynamoDBTable(tableName="StateInfo")
public class StateInfo {
    List<PlanetInfo> planets;
    List<RocketInfo> rockets;
    String id;

    public StateInfo() {}

    public StateInfo(List<PlanetInfo> planets, List<RocketInfo> rockets) {
        this.planets = planets;
        this.rockets = rockets;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public List<PlanetInfo> getPlanets() {
        return planets;
    }

    public List<RocketInfo> getRockets() {
        return rockets;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setPlanets(List<PlanetInfo> planets) {
        this.planets = planets;
    }

    public void setRockets(List<RocketInfo> rockets) {
        this.rockets = rockets;
    }
}
