package com.hacknite.model.request;

public enum ActionType {
    BRANCH_UPDATED, BRANCH_DELETED, PULL_REQUEST_CREATED, PULL_REQUEST_REVIEWED, PULL_REQUEST_MERGED, PULL_REQUEST_DELETED, BRANCH_CREATED;
}
