name: Java CI with Gradle
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        AWS_DYNAMODB_ENDPOINT: ${{ secrets.AWS_DYNAMODB_ENDPOINT}}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY}}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY}}
      run: ./gradlew build
    - name: Inspect artifact
      run: ls -R
    - name: Copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        username:  ${{ secrets.SSH_USERNAME }}
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        source: '.'
        target: './build/libs/pr-game-be-0.0.1-SNAPSHOT.jar'
    - name: Executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        username:  ${{ secrets.SSH_USERNAME }}
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        script: java -jar build/libs/pr-game-be-0.0.1-SNAPSHOT.jar
